# Import Modules and Read Data

In [44]:
import pandas
from collections import defaultdict

stats_dataset_path = "../data/raw/player_stats_season.csv"
players_dataset_path = "../data/raw/players.csv"
stats_df = pandas.read_csv(stats_dataset_path)
players_df = pandas.read_csv(players_dataset_path)

node_list_output_path = "../data/gephi-node-list.csv"
edge_list_output_path = "../data/gephi-edge-list-fantasy.csv"

print(stats_df.columns, "\n")
print(players_df.columns)

Index(['season', 'season_type', 'player_id', 'player_name',
       'player_display_name', 'position', 'position_group', 'headshot_url',
       'games', 'recent_team', 'completions', 'attempts', 'passing_yards',
       'passing_tds', 'interceptions', 'sacks', 'sack_yards', 'sack_fumbles',
       'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch',
       'passing_first_downs', 'passing_epa', 'passing_2pt_conversions', 'pacr',
       'dakota', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles',
       'rushing_fumbles_lost', 'rushing_first_downs', 'rushing_epa',
       'rushing_2pt_conversions', 'receptions', 'targets', 'receiving_yards',
       'receiving_tds', 'receiving_fumbles', 'receiving_fumbles_lost',
       'receiving_air_yards', 'receiving_yards_after_catch',
       'receiving_first_downs', 'receiving_epa', 'receiving_2pt_conversions',
       'racr', 'target_share', 'air_yards_share', 'wopr', 'special_teams_tds',
       'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

Index(['status', 'display_name', 'first_name', 'last_name', 'esb_id',
       'gsis_id', 'birth_date', 'college_name', 'position_group', 'position',
       'jersey_number', 'height', 'weight', 'years_of_experience', 'team_abbr',
       'team_seq', 'current_team_id', 'football_name', 'entry_year',
       'rookie_year', 'draft_club', 'college_conference',
       'status_description_abbr', 'status_short_description', 'gsis_it_id',
       'short_name', 'smart_id', 'headshot', 'draft_number', 'draftround',
       'uniform_number', 'suffix'],
      dtype='object')

In [45]:
stats_df

,season,season_type,player_id,player_name,player_display_name,position,position_group,headshot_url,games,recent_team,...,receiving_first_downs,receiving_epa,receiving_2pt_conversions,racr,target_share,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr
0,1999,REG,00-0000003,NaN,Abdul-Karim al-Jabbar,RB,RB,NaN,13,CLE,...,5,1.057477,0,0.000000,0.054591,NaN,NaN,0,64.70,81.70
1,1999,REG,00-0000007,NaN,Rabih Abdullah,RB,RB,NaN,4,TB,...,0,-2.089564,0,0.000000,0.048387,NaN,NaN,0,2.30,4.30
2,1999,REG,00-0000104,NaN,Troy Aikman,QB,QB,NaN,14,DAL,...,0,NaN,0,NaN,NaN,NaN,NaN,0,167.80,167.80
3,1999,REG,00-0000145,NaN,Derrick Alexander,WR,WR,NaN,16,KC,...,31,22.726649,0,0.000000,0.218220,NaN,NaN,0,109.40,163.40
4,1999,REG,00-0000166,NaN,Stephen Alexander,TE,TE,NaN,15,WAS,...,18,16.415007,0,0.000000,0.096436,NaN,NaN,0,49.80,77.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33631,2024,REG+POST,00-0039917,M.Penix,Michael Penix,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,5,ATL,...,0,NaN,0,NaN,NaN,NaN,NaN,0,44.10,44.10
33632,2024,REG+POST,00-0039918,C.Williams,Caleb Williams,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,17,CHI,...,0,NaN,0,NaN,NaN,NaN,NaN,0,254.54,254.54
33633,2024,REG+POST,00-0039919,R.Odunze,Rome Odunze,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,17,CHI,...,37,16.061161,0,0.525036,0.192015,0.335493,0.522868,0,90.90,144.90
33634,2024,REG+POST,00-0039920,M.Corley,Malachi Corley,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,5,NYJ,...,1,-3.643815,0,0.320000,0.046512,0.062972,0.113848,0,4.20,7.20
33635,2024,REG+POST,00-0039921,T.Benson,Trey Benson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,12,ARI,...,3,3.103831,0,-3.105263,0.045113,-0.023691,0.051086,0,41.00,47.00

In [46]:
players_df

,status,display_name,first_name,last_name,esb_id,gsis_id,birth_date,college_name,position_group,position,...,status_description_abbr,status_short_description,gsis_it_id,short_name,smart_id,headshot,draft_number,draftround,uniform_number,suffix
0,RET,'Omar Ellison,'Omar,Ellison,ELL711319,00-0004866,1971-10-08,NaN,WR,WR,...,NaN,NaN,NaN,NaN,3200454c-4c71-1319-728e-d49d3d236f8f,NaN,NaN,NaN,NaN,NaN
1,ACT,A'Shawn Robinson,A'Shawn,Robinson,ROB367960,00-0032889,1995-03-21,Alabama,DL,DE,...,A01,Active,43335.0,A.Robinson,3200524f-4236-7960-bf20-bc060ac0f49c,https://static.www.nfl.com/image/upload/f_auto...,46.0,2.0,94,NaN
2,RES,A.J. Arcuri,A.J.,Arcuri,ARC716900,00-0037845,1997-08-13,Michigan State,OL,T,...,R23,Reserve/Future,54726.0,A.Arcuri,32004152-4371-6900-5185-8cdd66b2ad11,https://static.www.nfl.com/image/upload/f_auto...,261.0,7.0,61,NaN
3,ACT,A.J. Barner,A.J.,Barner,BAR235889,00-0039793,2002-05-03,Michigan,TE,TE,...,A01,Active,57242.0,A.Barner,32004241-5223-5889-95d9-0ba3aeeb36ed,https://static.www.nfl.com/image/upload/f_auto...,121.0,4.0,88,NaN
4,RES,A.J. Bouye,Arlandus,Bouye,BOU651714,00-0030228,1991-08-16,Central Florida,DB,CB,...,R01,R/Injured,40688.0,A.Bouye,3200424f-5565-1714-cb38-07c822111a12,https://static.www.nfl.com/image/private/f_aut...,NaN,NaN,24,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20749,CUT,Zuri Henry,Zuri,Henry,HEN713594,00-0039689,2000-04-12,Texas-El Paso,OL,T,...,W03,Waivers/No Rec.,57839.0,Z.Henry,32004845-4e71-3594-d6f6-5f3aaca3acfc,NaN,NaN,NaN,65,NaN
20750,RET,Zuriel Smith,Zuriel,Smith,SMI828252,00-0022024,1980-01-15,NaN,WR,WR,...,NaN,NaN,NaN,NaN,3200534d-4982-8252-c800-85b370612021,NaN,NaN,NaN,NaN,NaN
20751,CUT,Zurlon Tipton,Zurlon,Tipton,TIP645432,00-0030855,1989-04-27,Central Michigan,RB,RB,...,A01,Active,41693.0,NaN,32005449-5064-5432-923a-94c7fae9b469,https://static.www.nfl.com/image/private/f_aut...,NaN,NaN,NaN,NaN
20752,DEV,Zyon Gilbert,Zyon,Gilbert,GIL144859,00-0037373,1999-02-04,Florida Atlantic,DB,CB,...,P02,Prac Sq.; Inj,54958.0,Z.Gilbert,32004749-4c14-4859-6e4a-327bb4fcec5a,https://static.www.nfl.com/image/upload/f_auto...,NaN,NaN,42,NaN
20753,ACT,Zyon McCollum,Zyon,McCollum,MCC496223,00-0037268,1999-05-03,Sam Houston State,DB,CB,...,A01,Active,54622.0,Z.McCollum,32004d43-4349-6223-dfc9-cd33beb7fa6f,https://static.www.nfl.com/image/upload/f_auto...,157.0,5.0,27,NaN

# Clean Data

In [47]:
stats_df = stats_df[stats_df["season_type"] == "REG+POST"]

In [48]:
colleges_df = players_df[["gsis_id", "college_name", "college_conference"]]
colleges_df = colleges_df.rename(columns={"gsis_id": "player_id"})

In [49]:
merged_df = pandas.merge(stats_df, colleges_df, on="player_id")

In [50]:
columns = ["player_id", "player_display_name", "season", "recent_team", "position", 
           "college_name", "college_conference", "fantasy_points"]

data = merged_df[columns]
data = data.dropna()
print("Number of players:", data["player_id"].nunique())

Number of players: 1962

# Create Node List

In [51]:
node_list_df = data.drop_duplicates(subset="player_id", keep="last")

In [52]:
total_fantasy_points = defaultdict(int)
for index, row in data.iterrows():
    total_fantasy_points[row.player_id] += row.fantasy_points
    
for key, value in total_fantasy_points.items():
    index = node_list_df[node_list_df["player_id"] == key].index
    node_list_df.loc[index, "fantasy_points"] = int(value)

In [53]:
node_list_df = node_list_df.drop("season", axis=1)
node_list_df = node_list_df.rename(columns={"player_id": "ID", "player_display_name": "name", "recent_team": "team"})
node_list_df

,ID,name,team,position,college_name,college_conference,fantasy_points
2949,00-0016919,Adam Vinatieri,NE,K,South Dakota State,Missouri Valley Football Conference,4.0
3746,00-0022531,Jason Peters,BUF,T,Arkansas,Southeastern Conference,12.0
4177,00-0022045,Terence Newman,DAL,CB,Kansas State,Big Twelve Conference,6.0
4266,00-0022923,DeAngelo Hall,ATL,FS,Virginia Tech,Atlantic Coast Conference,0.0
4755,00-0023252,Robbie Gould,CHI,K,Penn State,Big Ten Conference,0.0
...,...,...,...,...,...,...,...
15166,00-0039917,Michael Penix,ATL,QB,Washington,Pacific Twelve Conference,44.0
15167,00-0039918,Caleb Williams,CHI,QB,Southern California,Pacific Twelve Conference,254.0
15168,00-0039919,Rome Odunze,CHI,WR,Washington,Pacific Twelve Conference,90.0
15169,00-0039920,Malachi Corley,NYJ,WR,Western Kentucky,Conference USA,4.0
15170,00-0039921,Trey Benson,ARI,RB,Florida State,Atlantic Coast Conference,41.0

In [54]:
node_list_df.to_csv(node_list_output_path, index=False)

# Create Edge list

In [70]:
teams = defaultdict(list)
for index, row in data.iterrows():
    team = (row.recent_team, row.season)
    teams[team].append(row.player_id)

In [75]:
edges = defaultdict(int)
for team, players in teams.items():
    season = team[1]
    season_data = data.loc[data["season"] == season]
    players.sort()
    for i in range(len(players)):
        for j in range(i+1, len(players)):
            edge = (players[i], players[j])
            fantasy_i = float(season_data.loc[season_data["player_id"] == players[i], "fantasy_points"].sum())
            fantasy_j = float(season_data.loc[season_data["player_id"] == players[j], "fantasy_points"].sum())
            edges[edge] += fantasy_i + fantasy_j

In [84]:
edge_list = []
weights = []
for edge, weight in edges.items():
    weights.append(weight)

correction = abs(min(weights)) + 0.1

for edge, weight in edges.items():
    edge_list.append([edge[0], edge[1], (weight + correction)])
edge_list_df = pandas.DataFrame(edge_list, columns=["Source", "Target", "Weight"])
edge_list_df

           Source      Target   Weight
0      00-0020531  00-0021547   997.90
1      00-0021206  00-0022084   743.76
2      00-0016919  00-0019596   282.06
3      00-0016919  00-0022943    11.48
4      00-0019596  00-0022943  2194.24
...           ...         ...      ...
42753  00-0038797  00-0039811    95.42
42754  00-0038809  00-0039811    11.72
42755  00-0038996  00-0039811   124.42
42756  00-0039144  00-0039811    12.02
42757  00-0039146  00-0039811   154.12

[42758 rows x 3 columns]

In [86]:
edge_list_df.to_csv(edge_list_output_path, index=False)